import React from 'react';
import { useParams } from 'react-router-dom';
import annonces from '../../data/20Last.json';
//import Header from '../components/Header.jsx';
//import Carousel from '../components/Carousel.jsx';
//import Location from '../components/Location.jsx';
//import Owner from '../components/Owner.jsx';
//import Tags from '../components/Tags.jsx';
//import Rating from '../components/Rating.jsx';
//import Disclosure from '../components/Disclosure.jsx';
//import Footer from '../components/Footer.jsx';
