import React from 'react';
import { useParams } from 'react-router-dom';
import annonces from '../../data/20Last.json';
//import Header from '../components/Header/Header.jsx';
//import Carousel from '../components/Carousel/Carousel.jsx';
//import Location from '../components/Location/Location.jsx';
//import Owner from '../components/Owner/Owner.jsx';
//import Tags from '../components/Tags/Tags.jsx';
//import Rating from '../components/Rating/Rating.jsx';
//import Collapse from '../components/Collapse/Collapse.jsx';
//import Footer from '../components/Footer/Footer.jsx';
